name: Deployment Project
on: push
jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        run: actions/checkout@v3
      - name: Install Node Modules
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Linting
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
      - name: Testing
        run: npm test
      - name: Deploy
        run: echo "Deploying.."